/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_chengzhiya_mhdfverify_Verify */

#ifndef _Included_cn_chengzhiya_mhdfverify_Verify
#define _Included_cn_chengzhiya_mhdfverify_Verify
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_chengzhiya_mhdfverify_Verify
 * Method:    check
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_chengzhiya_mhdfverify_Verify_check
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
